### ISSUE TITLE
Password not founding

### ISSUE THREAD

**Issue by fittechy** [Ethical-H4CK3R/Instagram#11]
Hey great tool but when I tried it on a demo account it doesnt finds the password,and I have mentioned the password in the list also.Help!
Thanks

**Comment by Ethical-H4CK3R** [comment]
I am not sure, I try to fix it when I get a chance

**Comment by fittechy** [comment]
- [

- [ ] **_1._** 

](url)

**Comment by Virgula0** [comment]
It doesn't work also for me but I have see that if I type username like: name123 in the attempts the username is shown with the first capital letter: Name123.
is maybe for this that doesn't work with some accounts?

**Comment by Ethical-H4CK3R** [comment]
Sure.

**Comment by ekrem0** [comment]
@fittechy @Virgula0 I spent an hour to get this tool working but it did not work , After that I searched github for other tools then I found a actual tool that works okay , and the good part is its well documented , **I commenting this so that you would save your time** . here is the tool https://github.com/deathsec/instagram-py , its available via **pip** too. refer the repo for more info
