### ISSUE TITLE
obtaining proxy ip

### ISSUE THREAD

**Issue by lord5522** [Ethical-H4CK3R/Instagram#8]
i have been using kali 2.0 and it always stuck on obtaining proxy ip and lost connection  screen could you help me..

**Comment by Ethical-H4CK3R** [comment]
how is your Internet like? fast or slow, and are you able to access this [link](https://wtfismyip.com/text)

**Comment by lord5522** [comment]
yes i can access that link
and my internet is fast

**Comment by yahyoo** [comment]
same problem here ... it stuck at  n obtaining proxy ip or it says few arguments

root@kali:~/Desktop/Instagram# ls
Core  instagram.py  README.md  uo2n.txt
root@kali:~/Desktop/Instagram# python instagram.py
usage: instagram.py [-h] username wordlist
instagram.py: error: too few arguments

**Comment by Ethical-H4CK3R** [comment]
Usage: python instagram.py  myusername1301 mypasswordlist.lst

**Comment by deathsec** [comment]
Hey @lord5522  check my project its way better than this , it mimics **Instagram Android App** and uses tor to jump from location to location , its easy to setup in linux  , it does not block your computer or anything , runs efficiently even with large password list , all you need is tor server up and running which is easy to do in linux , so i suggest you boot into kali linux and try my tool  , but i did not document how to on tor server , you have to refer kali linux documentation on how to restart and start tor server 

[Instagram-Py - Simple Instagram Brute Force Attack script](https://github.com/deathsec/Instagram-Py)

no offense @Ethical-H4CK3R , but the problem is in your program , you seriously use subprocess in python to change tor circuit , that can hurt many things , try tor's official library for controlling tor its called stem and if you want a clean solution then fork my project mentioned above!

**Comment by Ethical-H4CK3R** [comment]
So basically you just improved the tor controller.

**Comment by Ethical-H4CK3R** [comment]
How does it work? Does it uses cookies to save the sessions, or something?
Can you explain please?

On Wed, Sep 27, 2017 at 6:48 AM, Ethical H4CK3R <ethical.hacker720@gmail.com

**Comment by deathsec** [comment]
@Ethical-H4CK3R see the algorithm section in the project README at https://github.com/deathsec/Instagram-Py for more information about how it works!

**Comment by Akashhacker22** [comment]
sir i have problem with obtaining proxy ip and shows error as "waiting for connection" even i had a high speed net,help me to over come this issue
